<?php

/**
 * @file
 * Functions to support theming forms in the Froglet theme.
 */

/**
 * Implements hook_preprocess_form().
 */
function froglet_preprocess_form(array &$variables) {
    //$variables['attributes']['novalidate'] = 'novalidate';
}

/**
 * Implements hook_preprocess_select().
 */
function froglet_preprocess_select(array &$variables) {
    //$variables['attributes']['class'][] = 'select-chosen';
}
